sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t bindian0509/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true bindian0509/react-test npm test

after_success:
  - docker build -t bindian0509/multi-client ./client
  - docker build -t bindian0509/multi-nginx ./nginx
  - docker build -t bindian0509/multi-server ./server
  - docker build -t bindian0509/multi-worker ./worker
  # docker login 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to docker hub
  - docker push bindian0509/multi-client
  - docker push bindian0509/multi-nginx
  - docker push bindian0509/multi-server
  - docker push bindian0509/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: multi-docker-app-nov
  bucket_path: docker-multi-nov
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY